/*
 * File: MPC_Params.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Mon Oct 23 12:48:07 2023
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                MPC_Params

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     4

/* Input Port  0 */
#define IN_PORT_0_NAME                 x_
#define INPUT_0_DIMS_ND                {4,1}
#define INPUT_0_NUM_ELEMS              4
#define INPUT_0_WIDTH                  4
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      2-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 p_max
#define INPUT_1_DIMS_ND                {4,1}
#define INPUT_1_NUM_ELEMS              4
#define INPUT_1_WIDTH                  4
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      2-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  0
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            9
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 v_
#define INPUT_2_DIMS_ND                {4,1}
#define INPUT_2_NUM_ELEMS              4
#define INPUT_2_WIDTH                  4
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  real_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      2-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  0
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            9
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125

/* Input Port  3 */
#define IN_PORT_3_NAME                 gbus
#define INPUT_3_DIMS_ND                {16,1}
#define INPUT_3_NUM_ELEMS              16
#define INPUT_3_WIDTH                  16
#define INPUT_DIMS_3_COL               1
#define INPUT_3_DTYPE                  real_T
#define INPUT_3_COMPLEX                COMPLEX_NO
#define IN_3_BUS_BASED                 0
#define IN_3_BUS_NAME
#define IN_3_DIMS                      2-D
#define INPUT_3_FEEDTHROUGH            1
#define IN_3_ISSIGNED                  0
#define IN_3_WORDLENGTH                8
#define IN_3_FIXPOINTSCALING           1
#define IN_3_FRACTIONLENGTH            9
#define IN_3_BIAS                      0
#define IN_3_SLOPE                     0.125
#define NUM_OUTPUTS                    1

/* Output Port  0 */
#define OUT_PORT_0_NAME                u
#define OUTPUT_0_DIMS_ND               {4,1}
#define OUTPUT_0_NUM_ELEMS             4
#define OUTPUT_0_WIDTH                 4
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     2-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125
#define NPARAMS                        16

/* Parameter 0 */
#define PARAMETER_0_NAME               h_
#define PARAMETER_0_DTYPE              real_T
#define PARAMETER_0_COMPLEX            COMPLEX_NO

/* Parameter 1 */
#define PARAMETER_1_NAME               n_
#define PARAMETER_1_DTYPE              real_T
#define PARAMETER_1_COMPLEX            COMPLEX_NO

/* Parameter 2 */
#define PARAMETER_2_NAME               ni_
#define PARAMETER_2_DTYPE              real_T
#define PARAMETER_2_COMPLEX            COMPLEX_NO

/* Parameter 3 */
#define PARAMETER_3_NAME               paso_
#define PARAMETER_3_DTYPE              real_T
#define PARAMETER_3_COMPLEX            COMPLEX_NO

/* Parameter 4 */
#define PARAMETER_4_NAME               pv_
#define PARAMETER_4_DTYPE              real_T
#define PARAMETER_4_COMPLEX            COMPLEX_NO

/* Parameter 5 */
#define PARAMETER_5_NAME               Vbase_
#define PARAMETER_5_DTYPE              real_T
#define PARAMETER_5_COMPLEX            COMPLEX_NO

/* Parameter 6 */
#define PARAMETER_6_NAME               Pbase_
#define PARAMETER_6_DTYPE              real_T
#define PARAMETER_6_COMPLEX            COMPLEX_NO

/* Parameter 7 */
#define PARAMETER_7_NAME               T1
#define PARAMETER_7_DTYPE              real_T
#define PARAMETER_7_COMPLEX            COMPLEX_NO

/* Parameter 8 */
#define PARAMETER_8_NAME               T2
#define PARAMETER_8_DTYPE              real_T
#define PARAMETER_8_COMPLEX            COMPLEX_NO

/* Parameter 9 */
#define PARAMETER_9_NAME               T3
#define PARAMETER_9_DTYPE              real_T
#define PARAMETER_9_COMPLEX            COMPLEX_NO

/* Parameter 10 */
#define PARAMETER_10_NAME              T4
#define PARAMETER_10_DTYPE             real_T
#define PARAMETER_10_COMPLEX           COMPLEX_NO

/* Parameter 11 */
#define PARAMETER_11_NAME              z1
#define PARAMETER_11_DTYPE             real_T
#define PARAMETER_11_COMPLEX           COMPLEX_NO

/* Parameter 12 */
#define PARAMETER_12_NAME              z2
#define PARAMETER_12_DTYPE             real_T
#define PARAMETER_12_COMPLEX           COMPLEX_NO

/* Parameter 13 */
#define PARAMETER_13_NAME              z3
#define PARAMETER_13_DTYPE             real_T
#define PARAMETER_13_COMPLEX           COMPLEX_NO

/* Parameter 14 */
#define PARAMETER_14_NAME              z4
#define PARAMETER_14_DTYPE             real_T
#define PARAMETER_14_COMPLEX           COMPLEX_NO

/* Parameter 15 */
#define PARAMETER_15_NAME              px_
#define PARAMETER_15_DTYPE             real_T
#define PARAMETER_15_COMPLEX           COMPLEX_NO
#define SAMPLE_TIME_0                  2e-3
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             1
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S)                  ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S)                  ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S)                  ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S)                  ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S)                  ssGetSFcnParam(S, 4)
#define PARAM_DEF5(S)                  ssGetSFcnParam(S, 5)
#define PARAM_DEF6(S)                  ssGetSFcnParam(S, 6)
#define PARAM_DEF7(S)                  ssGetSFcnParam(S, 7)
#define PARAM_DEF8(S)                  ssGetSFcnParam(S, 8)
#define PARAM_DEF9(S)                  ssGetSFcnParam(S, 9)
#define PARAM_DEF10(S)                 ssGetSFcnParam(S, 10)
#define PARAM_DEF11(S)                 ssGetSFcnParam(S, 11)
#define PARAM_DEF12(S)                 ssGetSFcnParam(S, 12)
#define PARAM_DEF13(S)                 ssGetSFcnParam(S, 13)
#define PARAM_DEF14(S)                 ssGetSFcnParam(S, 14)
#define PARAM_DEF15(S)                 ssGetSFcnParam(S, 15)
#define IS_PARAM_DOUBLE(pVal)          (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

extern void MPC_Params_Outputs_wrapper(const real_T *x_,
  const real_T *p_max,
  const real_T *v_,
  const real_T *gbus,
  real_T *u,
  const real_T *h_, const int_T p_width0,
  const real_T *n_, const int_T p_width1,
  const real_T *ni_, const int_T p_width2,
  const real_T *paso_, const int_T p_width3,
  const real_T *pv_, const int_T p_width4,
  const real_T *Vbase_, const int_T p_width5,
  const real_T *Pbase_, const int_T p_width6,
  const real_T *T1, const int_T p_width7,
  const real_T *T2, const int_T p_width8,
  const real_T *T3, const int_T p_width9,
  const real_T *T4, const int_T p_width10,
  const real_T *z1, const int_T p_width11,
  const real_T *z2, const int_T p_width12,
  const real_T *z3, const int_T p_width13,
  const real_T *z4, const int_T p_width14,
  const real_T *px_, const int_T p_width15);

/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)

/* Function: mdlCheckParameters =============================================
 * Abstract:
 *     Verify parameter definitions and types.
 */
static void mdlCheckParameters(SimStruct *S)
{
  int paramIndex = 0;
  bool invalidParam = false;

  /* All parameters must match the S-function Builder Dialog */
  {
    const mxArray *pVal0 = ssGetSFcnParam(S, 0);
    if (!IS_PARAM_DOUBLE(pVal0)) {
      invalidParam = true;
      paramIndex = 0;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal1 = ssGetSFcnParam(S, 1);
    if (!IS_PARAM_DOUBLE(pVal1)) {
      invalidParam = true;
      paramIndex = 1;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal2 = ssGetSFcnParam(S, 2);
    if (!IS_PARAM_DOUBLE(pVal2)) {
      invalidParam = true;
      paramIndex = 2;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal3 = ssGetSFcnParam(S, 3);
    if (!IS_PARAM_DOUBLE(pVal3)) {
      invalidParam = true;
      paramIndex = 3;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal4 = ssGetSFcnParam(S, 4);
    if (!IS_PARAM_DOUBLE(pVal4)) {
      invalidParam = true;
      paramIndex = 4;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal5 = ssGetSFcnParam(S, 5);
    if (!IS_PARAM_DOUBLE(pVal5)) {
      invalidParam = true;
      paramIndex = 5;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal6 = ssGetSFcnParam(S, 6);
    if (!IS_PARAM_DOUBLE(pVal6)) {
      invalidParam = true;
      paramIndex = 6;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal7 = ssGetSFcnParam(S, 7);
    if (!IS_PARAM_DOUBLE(pVal7)) {
      invalidParam = true;
      paramIndex = 7;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal8 = ssGetSFcnParam(S, 8);
    if (!IS_PARAM_DOUBLE(pVal8)) {
      invalidParam = true;
      paramIndex = 8;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal9 = ssGetSFcnParam(S, 9);
    if (!IS_PARAM_DOUBLE(pVal9)) {
      invalidParam = true;
      paramIndex = 9;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal10 = ssGetSFcnParam(S, 10);
    if (!IS_PARAM_DOUBLE(pVal10)) {
      invalidParam = true;
      paramIndex = 10;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal11 = ssGetSFcnParam(S, 11);
    if (!IS_PARAM_DOUBLE(pVal11)) {
      invalidParam = true;
      paramIndex = 11;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal12 = ssGetSFcnParam(S, 12);
    if (!IS_PARAM_DOUBLE(pVal12)) {
      invalidParam = true;
      paramIndex = 12;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal13 = ssGetSFcnParam(S, 13);
    if (!IS_PARAM_DOUBLE(pVal13)) {
      invalidParam = true;
      paramIndex = 13;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal14 = ssGetSFcnParam(S, 14);
    if (!IS_PARAM_DOUBLE(pVal14)) {
      invalidParam = true;
      paramIndex = 14;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal15 = ssGetSFcnParam(S, 15);
    if (!IS_PARAM_DOUBLE(pVal15)) {
      invalidParam = true;
      paramIndex = 15;
      goto EXIT_POINT;
    }
  }

 EXIT_POINT:
  /*if (invalidParam) {
    static char parameterErrorMsg[1024];
    sprintf(parameterErrorMsg,
            "The data type and or complexity of parameter %d does not match the "
            "information specified in the S-function Builder dialog. "
            "For non-double parameters you will need to cast them using int8, int16, "
            "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
    ssSetLocalErrorStatus(S, parameterErrorMsg);
  }*/

  return;
}

#endif                                 /* MDL_CHECK_PARAMETERS */

/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(inputDimsInfo);
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);      /* Number of expected parameters */

#if defined(MATLAB_MEX_FILE)

  if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
    mdlCheckParameters(S);
    if (ssGetErrorStatus(S) != NULL) {
      return;
    }
  } else {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

#endif

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  //ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssAllowSignalsWithMoreThan2D(S);
  inputDimsInfo.numDims = 2;
  inputDimsInfo.width = INPUT_0_NUM_ELEMS;
  int_T in0Dims[] = INPUT_0_DIMS_ND;
  inputDimsInfo.dims = in0Dims;
  ssSetInputPortDimensionInfo(S, 0, &inputDimsInfo);
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /* Input Port 1 */
  inputDimsInfo.numDims = 2;
  inputDimsInfo.width = INPUT_1_NUM_ELEMS;
  int_T in1Dims[] = INPUT_1_DIMS_ND;
  inputDimsInfo.dims = in1Dims;
  ssSetInputPortDimensionInfo(S, 1, &inputDimsInfo);
  ssSetInputPortDataType(S, 1, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /* Input Port 2 */
  inputDimsInfo.numDims = 2;
  inputDimsInfo.width = INPUT_2_NUM_ELEMS;
  int_T in2Dims[] = INPUT_2_DIMS_ND;
  inputDimsInfo.dims = in2Dims;
  ssSetInputPortDimensionInfo(S, 2, &inputDimsInfo);
  ssSetInputPortDataType(S, 2, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

  /* Input Port 3 */
  inputDimsInfo.numDims = 2;
  inputDimsInfo.width = INPUT_3_NUM_ELEMS;
  int_T in3Dims[] = INPUT_3_DIMS_ND;
  inputDimsInfo.dims = in3Dims;
  ssSetInputPortDimensionInfo(S, 3, &inputDimsInfo);
  ssSetInputPortDataType(S, 3, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 3, 1);/*direct input signal access*/
  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  int_T out0Dims[] = OUTPUT_0_DIMS_ND;
  outputDimsInfo.dims = out0Dims;
  ssSetOutputPortDimensionInfo(S, 0, &outputDimsInfo);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "10.6");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO

static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(portDimsInfo);
  int_T dims[2];

  /* Setting default dimensions for input port 0 */
  portDimsInfo.width = INPUT_0_NUM_ELEMS;
  dims[0] = INPUT_0_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 0) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 0, 1 , 1);
  }

  /* Setting default dimensions for input port 1 */
  portDimsInfo.width = INPUT_1_NUM_ELEMS;
  dims[0] = INPUT_1_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 1) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 1, 1 , 1);
  }

  /* Setting default dimensions for input port 2 */
  portDimsInfo.width = INPUT_2_NUM_ELEMS;
  dims[0] = INPUT_2_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 2) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 2, 1 , 1);
  }

  /* Setting default dimensions for input port 3 */
  portDimsInfo.width = INPUT_3_NUM_ELEMS;
  dims[0] = INPUT_3_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 3) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 3, 1 , 1);
  }

  /* Setting default dimensions for output port 0 */
  portDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  dims[0] = OUTPUT_0_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 0) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 0, &portDimsInfo);
  }

  return;
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
  const char_T *rtParamNames[] = { "P1", "P2", "P3", "P4", "P5", "P6", "P7",
    "P8", "P9", "P10", "P11", "P12", "P13", "P14", "P15", "P16" };

  ssRegAllTunableParamsAsRunTimeParams(S, rtParamNames);
}

#endif

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const real_T *x_ = (real_T *) ssGetInputPortRealSignal(S, 0);
  const real_T *p_max = (real_T *) ssGetInputPortRealSignal(S, 1);
  const real_T *v_ = (real_T *) ssGetInputPortRealSignal(S, 2);
  const real_T *gbus = (real_T *) ssGetInputPortRealSignal(S, 3);
  real_T *u = (real_T *) ssGetOutputPortRealSignal(S, 0);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const int_T p_width3 = mxGetNumberOfElements(PARAM_DEF3(S));
  const int_T p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
  const int_T p_width5 = mxGetNumberOfElements(PARAM_DEF5(S));
  const int_T p_width6 = mxGetNumberOfElements(PARAM_DEF6(S));
  const int_T p_width7 = mxGetNumberOfElements(PARAM_DEF7(S));
  const int_T p_width8 = mxGetNumberOfElements(PARAM_DEF8(S));
  const int_T p_width9 = mxGetNumberOfElements(PARAM_DEF9(S));
  const int_T p_width10 = mxGetNumberOfElements(PARAM_DEF10(S));
  const int_T p_width11 = mxGetNumberOfElements(PARAM_DEF11(S));
  const int_T p_width12 = mxGetNumberOfElements(PARAM_DEF12(S));
  const int_T p_width13 = mxGetNumberOfElements(PARAM_DEF13(S));
  const int_T p_width14 = mxGetNumberOfElements(PARAM_DEF14(S));
  const int_T p_width15 = mxGetNumberOfElements(PARAM_DEF15(S));
  const real_T *h_ = (const real_T *) mxGetData(PARAM_DEF0(S));
  const real_T *n_ = (const real_T *) mxGetData(PARAM_DEF1(S));
  const real_T *ni_ = (const real_T *) mxGetData(PARAM_DEF2(S));
  const real_T *paso_ = (const real_T *) mxGetData(PARAM_DEF3(S));
  const real_T *pv_ = (const real_T *) mxGetData(PARAM_DEF4(S));
  const real_T *Vbase_ = (const real_T *) mxGetData(PARAM_DEF5(S));
  const real_T *Pbase_ = (const real_T *) mxGetData(PARAM_DEF6(S));
  const real_T *T1 = (const real_T *) mxGetData(PARAM_DEF7(S));
  const real_T *T2 = (const real_T *) mxGetData(PARAM_DEF8(S));
  const real_T *T3 = (const real_T *) mxGetData(PARAM_DEF9(S));
  const real_T *T4 = (const real_T *) mxGetData(PARAM_DEF10(S));
  const real_T *z1 = (const real_T *) mxGetData(PARAM_DEF11(S));
  const real_T *z2 = (const real_T *) mxGetData(PARAM_DEF12(S));
  const real_T *z3 = (const real_T *) mxGetData(PARAM_DEF13(S));
  const real_T *z4 = (const real_T *) mxGetData(PARAM_DEF14(S));
  const real_T *px_ = (const real_T *) mxGetData(PARAM_DEF15(S));
  MPC_Params_Outputs_wrapper(x_, p_max, v_, gbus, u, h_, p_width0, n_, p_width1,
    ni_, p_width2, paso_, p_width3, pv_, p_width4, Vbase_, p_width5, Pbase_,
    p_width6, T1, p_width7, T2, p_width8, T3, p_width9, T4, p_width10, z1,
    p_width11, z2, p_width12, z3, p_width13, z4, p_width14, px_, p_width15);
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
